version: '2'

services:
  app:
    build: .
    ports:
      - '5175:5175'
      - '5176:80'
    volumes:
      - '.:/app'
    depends_on:
      - 'postgres'

  postgres:
    image: 'postgres:15.3'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - '.:/app'
    environment:
      - POSTGRES_PASSWORD=wow

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g

  kibana:
    depends_on:
      - 'elasticsearch'
    image: kibana:7.17.0
    ports:
      - 5601:5601

volumes:
  postgres:
  esdata:
