version: '2'

services:
  app:
    build: .
    ports:
      - '5176:80'
    volumes:
      - '.:/app'
    depends_on:
      - 'postgres'

  postgres:
    image: 'postgres:15.3'
    tmpfs:
      - '/var/lib/postgresql/data'
    volumes:
      - '.:/app'
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
    tmpfs:
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
