version: '2'

services:
  app:
    build: .
    ports:
      - '5176:80'
    volumes:
      - '.:/app'
    depends_on:
      - 'postgres'

  postgres:
    image: 'postgres:15.3'
    tmpfs:
      - '/var/lib/postgresql/data'
    volumes:
      - '.:/app'
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
