<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class AddDefaultCustomFields extends Migration
{
    public function up()
    {
      $fieldsData = <<<EOD
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'current_state', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='location_current'), 2, 'Current state/province', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'current_country', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='location_current'), 3, 'Current country', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'work_sectors_wish_work', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_work'), 4, 'Work sectors you wish for your work to impact', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:40:47');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'work_regional_focus', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_work'), 5, 'Work regional focus', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:45:50');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'programming_languages', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_knowledge'), 3, 'Programming languages', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:27');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'kinds_writing_want_to_learn', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='interested_in'), 5, 'Kinds of writing you want to learn', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:47:04');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'main_topics_focus', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_work'), 6, 'Main topics/issues at the focus of your work', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:46');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'areas_of_study', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='educational_information'), 3, 'Areas of study', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:47:16');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'primary_channels', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_work'), 7, 'Primary channels through which your work is expressed', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:37');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'languages_spoken', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_knowledge'), 2, 'Languages spoken', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:59');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'other_disciplines', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_work'), 2, 'Other disciplines in which you''ve been trained', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:41');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'kinds_of_writing', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_knowledge'), 4, 'Kinds of writing', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:47:08');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'languages_want_to_learn', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='interested_in'), 3, 'Languages that you want to learn', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:52');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'home_city', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='location_information'), 1, 'Home city', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'home_state', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='location_information'), 2, 'Home state/province', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'home_country', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='location_information'), 3, 'Home country', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'current_city', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='location_current'), 1, 'Current city', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'degree_granted', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='educational_information'), 2, 'Degree granted', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'employer_name', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='professional_information'), 1, 'Employer name', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'job_title', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='professional_information'), 2, 'Job title', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'industry', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='professional_information'), 3, 'Industry', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'primary_discipline', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_work'), 1, 'Primary discipline', NULL, '{ "allowNewValues": true }', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'primary_work_sector', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_work'), 3, 'Primary work sector', NULL, '{ "allowNewValues": true }', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'fav_foods', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='favorites'), 3, 'One of your favorite foods', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('long_text', 'focus_of_work_this_year', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='my_information'), 1, 'Focus of work for this year', NULL, '{}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'website_link', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 2, 'Website link', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'facebook_link', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 3, 'Facebook link', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'twitter_link', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 4, 'Twitter link', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'mastodon_link', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 5, 'Mastodon link', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'instagram_link', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 6, 'Instagram link', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'snapchat_link', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 7, 'Snapchat link', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'other_link', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 8, 'Other link', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'linkedin_link', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 8, 'LinkedIn link', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'link_liked_article', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='favorites'), 1, 'Link to one article from the past year that you loved', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'link_to_fav_songs', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='favorites'), 2, 'Link to one of your favorite songs', NULL, '{"isLink": true}', '2023-12-01 06:19:30.777015', '2023-12-01 06:19:30.777015');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'working_groups', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='working_groups_projects'), 1, 'Working groups', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:45:55');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'alma_mater', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='educational_information'), 1, 'Alma mater', NULL, '{"isLink": false, "tagName": "", "allowMultiple": false, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:37:25');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'current_skills', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='current_knowledge'), 1, 'Specific skills or expertise', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:07');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags_range', 'affiliation', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='affiliation'), 1, 'Affiliation', NULL, '{"isLink": false, "tagName": "Type", "allowMultiple": false, "allowNewValues": true, "possibleValues": ["CEO"], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:40:03');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'skills_want_to_learn', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='interested_in'), 2, 'Skills that you are want to learn or develop', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:16');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'projects', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='working_groups_projects'), 2, 'Projects', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:19');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'programming_want_to_learn', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='interested_in'), 4, 'Programming languages and frameworks that you want to learn', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:46:23');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('tags', 'issues_interested_exploring', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='interested_in'), 1, 'Issues you are interested in exploring', NULL, '{"isLink": false, "tagName": "", "allowMultiple": true, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false}', '2023-12-01 06:19:30.777015', '2023-12-01 11:47:12');
      INSERT INTO custom_fields (input_type, machine_name, model_name, group_id, "order", title, description, metadata, created_at, updated_at) VALUES ('short_text', 'url_to_photo', 'People', (SELECT id FROM custom_field_groups WHERE machine_name='online_presence'), 1, 'URL to a photo', NULL, '{"isLink": true, "tagName": "", "allowMultiple": false, "allowNewValues": true, "possibleValues": [""], "shareUserValues": false, "isImportProfileImageLink": true}', '2023-12-01 06:19:30.777015', '2023-12-04 20:21:00');
      EOD;

      $this->db->query($fieldsData);
    }

    public function down()
    {}
}
